// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a C4 community web.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Gamanet.C4.SimpleInterfaces.Plugins;
using System.Runtime.CompilerServices;

[assembly: FrameworkInfo("Gamanet.C4.SDK.Framework4.Registrator.DriverRegistrator, Gamanet.C4.SDK.Framework4")]
[assembly: PackageInfo("2bf619a9-bb5d-4f37-8fa3-7f014d5191c5", "SimpleDriver")]
[assembly: InternalsVisibleTo("Gamanet.C4.Driver.SimpleDriver.Should")]